#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jul 25 21:44:35 CST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=8
shaderPack=ComplementaryReimagined_r5.5.1 + EuphoriaPatches_1.6.4 + Colorwheel_0.2.3
