
["Surprising Loot Config"]
	#Maximum allowed time (ms) between right-click and container open before spawn trigger is discarded.
	#Range: > 1
	timeStampIntervalMs = 500
	#Maximum allowed Manhattan distance between player position on right-click and container open.
	#Range: 0.0 ~ 2.147483647E9
	maxBlockPosDist = 1.0
	#Enable debug logs for spawn trigger rejection reasons.
	debugLogs = true

